name: probfem
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python=3.10
  # mandatory packages
  - matplotlib
  - numpy<2.0.0 # otherwise, compatibility with cholmod breaks
  - pandas
  - pot # provides optimal transport package (for wasserstein distance)
  - python-gmsh
  - scikit-sparse=0.4.12 # provides cholmod library
  - scipy>=1.12.0 # provides scipy.sparse.diags_arra
  - seaborn
  - sympy
  # myjive import
  - myjive=0.1.14
  # support packages
  - pytest
