name: rmfem
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python=3.10
  # mandatory packages
  - matplotlib=3.5.2
  - numpy=1.23.5
  - sympy=1.12
  # myjive import
  - pip
  - pip:
    - myjive==0.1.7
  # support packages
  - pytest
