name: rmfem-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python=3.10
  # mandatory packages
  - matplotlib=3.5.2
  - numpy=1.23.5
  - sympy=1.12
  # support packages
  - black
  - pytest
  - spyder
