name: probfem-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # python version
  - python>=3.10
  # mandatory packages
  - pandas>=2.2.2
  - matplotlib>=3.5.2
  - numpy>=1.23.5
  - scipy>=1.12.0 # provides scipy.sparse.diags_array
  - seaborn>=0.13.2
  - sympy>=1.12
  # support packages
  - black
  - pytest
